# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
   wget https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip -O terraform.zip
   unzip terraform.zip 
   sudo mv terraform /usr/local/bin 
   rm terraform.zip
  displayName: 'terraform install'
- bash: terraform -v
  displayName: 'terraform version'
- bash: terraform init
  displayName: 'init teraform'
- script: terraform plan
  displayName: 'plan' 
  env:
   PREFIX: $(PREFIX)
   AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
   AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
   AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
   AZURE_TENANT_ID: $(AZURE_TENANT_ID)
   AZURE_REGION: $(AZURE_REGION)
   VSTS_TOKEN: $(VSTS_TOKEN)
   VSTS_POOL: $(VSTS_POOL)
   VSTS_ACCOUNT: $(VSTS_ACCOUNT)
   VM: $(VM)
   ADMIN_USERNAME: $(ADMIN_USERNAME)
   ADMIN_PASSWORD: $(ADMIN_PASSWORD)
   ADMIN_SSHKEYPATH: $(ADMIN_SSHKEYPATH)
   ADMIN_SSHKEYDATA: $(ADMIN_SSHKEYDATA)
- bash: terraform apply -auto-approve
  displayName: 'apply'
