# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: terraform -v
  displayName: 'terraform version'
- bash: terraform init
  displayName: 'terraform init'
- task: AzureCLI@1
  inputs:
    azureSubscription: 'TPE General Dev'
    scriptLocation: 'scriptPath'
    scriptPath: 'tfplan.sh'
    arguments: |
      tpe-keyvault 
      terraform-ukhogov
  env:
   TF_VAR_ADMIN_PASSWORD: $(TF_VAR_ADMIN_PASSWORD)
   TF_VAR_ADMIN_SSHKEYDATA: $(TF_VAR_ADMIN_SSHKEYDATA)
   TF_VAR_BRANCH: $(Build.SourceBranchName)   
  displayName: 'plan'