# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  - master

pr: none

variables:
  - group: agents-PRD-variables
  - name: AzureRegion
    value: UK South
  - name: PoolPrefix
    value: UKHO

pool:
  vmImage: 'ubuntu-latest'
container: ant59/terraform-azure-make:latest
steps:
- bash: terraform -v
  displayName: 'terraform version'
- task: AzureCLI@1
  inputs:
    azureSubscription: 'AzDo Live'
    scriptLocation: inlineScript
    inlineScript: |
      ACCOUNT="VSTS_ACCOUNT_$TF_VAR_ENVIRONMENT"
      TOKEN="VSTS_TOKEN_$TF_VAR_ENVIRONMENT"

      export TF_VAR_VSTS_ACCOUNT="${!ACCOUNT}"
      export TF_VAR_VSTS_TOKEN="${!TOKEN}"
      export TF_VAR_RUN_DATE=$(date +%F)

      cd terraform
      terraform init
      terraform plan -out=tfplan -input=false
      terraform apply "tfplan"
  env:
    ARM_SUBSCRIPTION_ID: $(TERRAFORM-SUBSCRIPTION-ID)
    ARM_TENANT_ID: $(TERRAFORM-TENANT-ID)
    ARM_ACCESS_KEY: $(TERRAFORM-ACCESS-KEY)
    ARM_CLIENT_ID: $(TERRAFORM-CLIENT-ID)
    ARM_CLIENT_SECRET: $(TERRAFORM-CLIENT-SECRET)
    TF_VAR_BRANCH: $(Build.SourceBranchName)   
    VSTS_ACCOUNT_DEV: $(VSTS-Account-DEV)
    VSTS_ACCOUNT_PRD: $(VSTS-Account-PRD)
    VSTS_TOKEN_DEV: $(VSTS-Token-DEV)
    VSTS_TOKEN_PRD: $(VSTS-Token-PRD)
    TF_VAR_SERVERNAMES: $(TF_VAR_SERVERNAMES)
    TF_VAR_ADMIN_USERNAME: $(VSTS-Admin-User)
    TF_VAR_ADMIN_PASSWORD: $(VSTS-Admin-Password)
    TF_VAR_ADMIN_SSHKEYPATH: $(VSTS-SskKeyPath)
    TF_VAR_ADMIN_SSHKEYDATA: $(VSTS-SshKeyData)
    TF_VAR_AZURE_REGION: $(AzureRegion)
    TF_VAR_VSTS_POOL_PREFIX: $(PoolPrefix)
  displayName: 'initialise, plan and apply'