# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - master

pr: none

pool:
  vmImage: 'ubuntu-latest'
container: ant59/terraform-azure-make:latest
steps:
- bash: terraform -v
  displayName: 'terraform version'
- task: AzureCLI@1
  inputs:
    azureSubscription: 'AzDo Live'
    scriptLocation: 'scriptPath'
    scriptPath: 'tfplan.sh'
  env:
   TF_VAR_BRANCH: $(Build.SourceBranchName)  
   TF_VAR_VSTS_ACCOUNT: $(TF_VAR_VSTS_ACCOUNT)
   TF_VAR_VSTS_TOKEN: $(TF_VAR_VSTS_TOKEN)
  displayName: 'initialise, plan and apply'
- task: AzureCLI@1
  displayName: restart agents
  inputs:
    azureSubscription: 'AzDo Live'
    scriptLocation: inlineScript
    inlineScript: |
      export TF_VAR_RUN_DATE=$(date +%F)
      make restart $TF_VAR_VSTS_ACCOUNT $TF_VAR_ENVIRONMENT $TF_VAR_RUN_DATE
  env:
   TF_VAR_BRANCH: $(Build.SourceBranchName)  
   TF_VAR_VSTS_ACCOUNT: $(TF_VAR_VSTS_ACCOUNT)
   TF_VAR_VSTS_TOKEN: $(TF_VAR_VSTS_TOKEN)
