#! /bin/bash

PROG=$(basename $0)

printerr() {
  echo "$@" 1>&2
}

usage() {
  printerr "Usage: $PROG [-d] [-k <key>] file"
  printerr "       $PROG -h"
  [ -n "$1" ] && exit 1
}

help() {
  usage
  printerr "          -d        decrypt. Default is to encrypt"
  printerr "          -h        help"
  printerr "          -k <key>  Key. Default \$ARM_ACCESS_KEY"
  exit 0
}

fail() { printerr "$@"; exit 1; }

while getopts ":df:hk:" o; do
    case "${o}" in
        d)
            DECRYPT=1
            ;;
        h)
            help
            ;;
        k)
            K=$OPTARG
            ;;
        *)
            usage 1
            ;;
    esac
done
shift $((OPTIND-1))

[ "$#" != "1" ] && usage && exit 0

KEY=${K:-$ARM_ACCESS_KEY}
FILE=$1

[ -z "$KEY" ] && fail "Key not specified"
[ ! -f "$FILE" ] && fail "$FILE: no such file"

OPENSSL="openssl enc -aes-256-cbc -md md5 -k $KEY"

if [ -n "$DECRYPT" ]
then
  base64 -d $FILE | $OPENSSL -d
else
  $OPENSSL -in $FILE | base64
fi

